language: android

android:
    components:
        - build-tools-22.0.1
        - android-21
        - extras
        - extra-android-m2repository
        - extra-google-google_play_services

script:
    - ./gradlew assembleFroyoRelease
    - ./gradlew assembleLatestRelease
    - ./gradlew test
